-- ============================================
-- USER TABLE (MASTER TABLE - ALL USERS)
-- ============================================
CREATE TABLE User_Table (
    ERP              NUMBER(5) PRIMARY KEY,
    name             VARCHAR2(100) NOT NULL,
    email            VARCHAR2(150) UNIQUE NOT NULL,
    user_password    VARCHAR2(16) NOT NULL,
    role             VARCHAR2(20) NOT NULL,
    phone_number     VARCHAR2(11) NOT NULL,
    verification_code VARCHAR2(10),
    code_expiry      TIMESTAMP,
    
    -- Constraints
    CONSTRAINT chk_email_domain CHECK (
        email LIKE '%@iba.edu.pk' OR email LIKE '%@khi.iba.edu.pk'
    ),
    CONSTRAINT chk_password_length CHECK (
        LENGTH(user_password) >= 8 AND LENGTH(user_password) <= 16
    ),
    CONSTRAINT chk_valid_role CHECK (role IN ('Student', 'BuildingIncharge', 'ProgramOffice')),
    CONSTRAINT chk_phone_format CHECK (
        REGEXP_LIKE(phone_number, '^03[0-9]{9}$')
    )
);

alter table user_table 
drop column verification_code;
alter table user_table 
drop column code_expiry;
ALTER TABLE User_Table 
ADD CONSTRAINT chk_erp_exact_5_digits CHECK (
    ERP >= 10000 AND ERP <= 99999
);

-- ============================================
-- STUDENT TABLE
-- ============================================
CREATE TABLE Student (
    ERP          NUMBER(5) PRIMARY KEY,
    program      VARCHAR2(10) NOT NULL,
    intake_year  NUMBER(4) NOT NULL,
    
    -- Foreign Key with CASCADE
    FOREIGN KEY (ERP) REFERENCES User_Table(ERP) ON DELETE CASCADE,
    
    -- Constraints
    CONSTRAINT chk_valid_program CHECK (program IN (
        'BBA', 'BSACF', 'BSECO', 'BSBA', 'BSSS', 'BSCS', 'BSEM', 'BSMT'
    ))
);
-- ============================================
-- BUILDING TABLE
-- ============================================
CREATE TABLE Building (
    building_id   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    building_name VARCHAR2(50) NOT NULL UNIQUE
);

-- ============================================
-- INCHARGE TABLE
-- ============================================
CREATE TABLE Incharge (
    incharge_id NUMBER(5) PRIMARY KEY,                     
    building_id NUMBER NOT NULL UNIQUE,
    
    -- Foreign Keys with CASCADE
    FOREIGN KEY (incharge_id) REFERENCES User_Table(ERP) ON DELETE CASCADE,
    FOREIGN KEY (building_id) REFERENCES Building(building_id) ON DELETE CASCADE
);

-- ============================================
-- ROOM TABLE
-- ============================================
CREATE TABLE Room (
    room_id      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    building_id  NUMBER NOT NULL,
    room_name    VARCHAR2(15) NOT NULL,
    room_type    VARCHAR2(20) NOT NULL,
    
    -- Foreign Key
    FOREIGN KEY (building_id) REFERENCES Building(building_id) ON DELETE CASCADE,
    
    -- Constraints
    CONSTRAINT chk_room_type CHECK (room_type IN ('CLASSROOM', 'BREAKOUT')),
    CONSTRAINT uk_room_building UNIQUE (building_id, room_name)
);

-- ============================================
-- SCHEDULE TABLE (ACADEMIC TIMETABLE)
-- ============================================
CREATE TABLE Schedule (
    schedule_id   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    room_id       NUMBER NOT NULL,
    day_of_week   VARCHAR2(10) NOT NULL,
    start_time    TIMESTAMP NOT NULL,
    end_time      TIMESTAMP NOT NULL,
    course_code   VARCHAR2(20) NOT NULL,
    
    -- Foreign Keys
    FOREIGN KEY (room_id) REFERENCES Room(room_id) ON DELETE CASCADE,
    
    -- Constraints
    CONSTRAINT chk_valid_day CHECK (UPPER(day_of_week) IN (
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'
    )),
    CONSTRAINT chk_time_order CHECK (end_time > start_time)
);
-- ============================================
-- BOOKING TABLE 
-- ============================================
CREATE TABLE Booking (
    booking_id      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ERP             NUMBER(5) NOT NULL,
    room_id         NUMBER NOT NULL,
    booking_date    DATE NOT NULL,

    start_time      TIMESTAMP NOT NULL,
    end_time        TIMESTAMP NOT NULL,
    purpose         VARCHAR2(500) NOT NULL,
    status          VARCHAR2(20) DEFAULT 'Approved',
    created_date    TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    -- Foreign Keys
    FOREIGN KEY (ERP) REFERENCES User_Table(ERP) ON DELETE CASCADE,
    FOREIGN KEY (room_id) REFERENCES Room(room_id) ON DELETE CASCADE,
    
    -- Constraints
    CONSTRAINT chk_booking_status CHECK (status IN ('Approved', 'Rejected', 'Cancelled')),
    CONSTRAINT chk_booking_time_order CHECK (end_time > start_time),
    CONSTRAINT chk_booking_duration CHECK (
        (end_time - start_time) <= INTERVAL '1' HOUR + INTERVAL '15' MINUTE
    ),
    CONSTRAINT uk_booking_time UNIQUE (room_id, booking_date, start_time, status) 
);


-- ============================================
-- ANNOUNCEMENT TABLE
-- ============================================
CREATE TABLE Announcement (
    announcement_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ERP             NUMBER(5) NOT NULL,
    title           VARCHAR2(100) NOT NULL,
    description     VARCHAR2(300),
    date_posted     TIMESTAMP NOT NULL,
    created_date    TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    -- Foreign Key
    FOREIGN KEY (ERP) REFERENCES User_Table(ERP) ON DELETE CASCADE
);


